#!/bin/bash

# Moodle Development Kit
# Copyright (C) 2012 Frédéric Massart - FMCorz.net
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# http://github.com/FMCorz/mdk

COMMAND="moodle-$1.py"
BIN=`which $COMMAND`

if [ -z "$BIN" ]
then
    if [ -n "${BASH_SOURCE[0]}" ]
    then
        SOURCE="${BASH_SOURCE[0]}"
        DIR="$( dirname "$SOURCE" )"
        while [ -h "$SOURCE" ]
        do
            SOURCE="$(readlink "$SOURCE")"
            [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
            DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
        done
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        BIN="$DIR/$COMMAND"
    fi
fi

if [ -z "$BIN" ] || [ ! -f "$BIN" ]
then
	echo "Unknown Moodle command..."
	exit 1
fi

if [ ! -x "$BIN" ]
then
    echo "Permission denied. $BIN is not executable."
    exit 1
fi

$BIN ${@:2}
exit $?
