#!/bin/bash

# Moodle Development Kit
# Copyright (C) 2012 Frédéric Massart - FMCorz.net
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# http://github.com/FMCorz/mdk

COMMAND=$1
ARGS=${@:2}

# Resolve a command
function resolve {
    PY="moodle-$1.py"
    if [[ $1 == "mdk.py" ]]; then
        PY="mdk.py"
    fi
    BIN=`which $PY`
    if [ -z "$BIN" ]
    then
        if [ -n "${BASH_SOURCE[0]}" ]
        then
            SOURCE="${BASH_SOURCE[0]}"
            DIR="$( dirname "$SOURCE" )"
            while [ -h "$SOURCE" ]
            do
                SOURCE="$(readlink "$SOURCE")"
                [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
                DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
            done
            DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
            BIN="$DIR/$PY"
        fi
    fi
    if [ -z "$BIN" ] || [ ! -f "$BIN" ]
    then
        exit 1
    fi
    echo "$BIN"
}

# Trying to use the new Python script, if not possible resume the bash script.
# This whole file should be removed in a later version.
echo "You are using a deprecated bash script." 1>&2
echo "Please update your symlink '`basename $0`'."  1>&2
MDK=`resolve 'mdk.py'`
if [ -n "$MDK" ] && [ -f "$MDK" ]; then
    CLI="`which python` $MDK $COMMAND $ARGS"
    echo "  ln -sf '$MDK' '$0'" 1>&2
    echo "" 1>&2
    echo "Executing: $CLI" 1>&2
    $CLI
    exit $?
fi
echo ""

# Checking if an alias exist for that command.
BIN=`resolve "alias"`
ALIAS=`$BIN show $COMMAND | tail -1`

if [ -n "$ALIAS" ]
then
    # It's a shell command. Let's substitute the arguments.
    if [[ ${ALIAS:0:1} == '!' ]]; then
        CMD="${ALIAS:1}"
        for ((I = 2; I <= $#; I++)); do
            ARG=${@:I:1}
            CMD=${CMD//\$$((I-1))/$ARG}
        done
        $CMD
        exit $?
    fi
    # If we're here, it's not a shell command. Let's parse the command and arguments.
    COMMAND=`echo $ALIAS | cut -d ' ' -f 1`
    ALIASARGS=`echo $ALIAS | cut -d ' ' -s -f 2-`
    ARGS="$ALIASARGS $ARGS"
fi

BIN=`resolve $COMMAND`

if [ $? == 1 ]
then
    echo "Unknown Moodle command '$1'..."
    exit 1
elif [ ! -x "$BIN" ]
then
    echo "Permission denied. '$BIN' is not executable."
    exit 1
fi

$BIN $ARGS
exit $?
